server:
  port: 8760
# eureka-client 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8752/eureka  # 服务地址/eureka (/eureka一定要加,否则启动直接报错TransportException: Cannot execute request on any known server)

# application-name
spring:
  application:
    name: SpringBootService1
# mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# spring启动横幅
  banner:
    location: classpath:static/banner/banner.txt

# mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.spring.demo.entity

# log4j2
logging:
  config: classpath:config/log4j2.xml